"""Test Decision Explainability with Running Mock Data.
Generates a Decision object using ReportingAgent and outputs JSON for frontend testing.
"""

import sys
import os
import json
from pathlib import Path
from datetime import datetime, timedelta

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.models import (
    CharacterSheet,
    Goal,
    Pillar,
    DailyReport,
    StatsDelta,
    SkillTree,
)
from src.reporting.agent import ReportingAgent
from src.memory.integration import sync_daily_report_to_memory
from src.memory.significance import SignificanceScorer
from src.memory.vector_store import SemanticMemory


def load_or_generate_mock_history():
    """Load mock history or generate it if it doesn't exist."""
    history_path = Path("debug/mock_history.json")
    
    if not history_path.exists():
        print("[!] mock_history.json not found. Generating...")
        # Import and run the generator
        import subprocess
        result = subprocess.run(
            [sys.executable, "debug/generate_mock_history.py"],
            cwd=os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            capture_output=True,
            text=True
        )
        if result.returncode != 0:
            print(f"[X] Error generating mock history: {result.stderr}")
            return []
    
    with open(history_path, "r") as f:
        logs = json.load(f)
    
    return logs


def convert_logs_to_daily_reports(logs):
    """Convert mock history logs to DailyReport objects."""
    reports = []
    
    for log in logs:
        # Create a basic DailyReport from the log entry
        # Extract sentiment and type from log
        sentiment = log.get("sentiment", "neutral")
        log_type = log.get("type", "routine")
        pillar = log.get("pillar", "PHYSICAL")
        
        # Create summary based on content
        summary = log["content"]
        
        # Extract wins, struggles, reflections based on type and sentiment
        wins = []
        struggles = []
        reflections = []
        
        if log_type in ["milestone", "correction", "insight"] and sentiment == "positive":
            wins.append(summary)
        elif log_type in ["failure", "warning", "emotion"] and sentiment == "negative":
            struggles.append(summary)
        elif log_type in ["insight", "correction"]:
            reflections.append(summary)
        
        report = DailyReport(
            date=log["date"],
            summary=summary,
            sentiment=sentiment,
            wins=wins,
            struggles=struggles,
            reflections=reflections,
            free_text="",
            tasks=[],
            stats_delta=StatsDelta(),
            new_tasks=[],
            new_skill_nodes=[],
        )
        
        reports.append(report)
    
    return reports


def create_running_goal():
    """Create a running goal for testing."""
    goal = Goal(
        id="goal_running_test",
        name="Run 5km, 3x per week",
        pillars=[Pillar.PHYSICAL],
        current_quests=["Go for a run once a week"],
        skill_level=6,
        needed_quests=["Run 3km", "Run 5km", "Run 7km"],
        roadmap=[],  # Will be generated by planner if needed
    )
    return goal


def create_test_character_sheet(reports):
    """Create a CharacterSheet with mock running data."""
    user_id = "test_decision_running"
    
    sheet = CharacterSheet(user_id=user_id)
    sheet.daily_reports = reports
    sheet.goals = [create_running_goal()]
    
    return sheet


def sync_reports_to_memory(sheet, user_id):
    """Sync all DailyReports to SemanticMemory with significance scoring."""
    print("\n[STEP] Syncing reports to memory (with significance gate)...")
    
    memory = SemanticMemory(user_id=user_id)
    scorer = SignificanceScorer()
    
    synced_count = 0
    skipped_count = 0
    
    for report in sheet.daily_reports:
        try:
            result = sync_daily_report_to_memory(
                memory=memory,
                report=report,
                user_id=user_id,
                significance_scorer=scorer,
                skip_significance_check=False,
            )
            
            # Count what was added vs skipped
            vector_chunks = result.get("vector_db_chunks", [])
            audit_chunks = result.get("audit_trail_chunks", [])
            
            synced_count += len(vector_chunks)
            skipped_count += len(audit_chunks) - len(vector_chunks)
            
        except Exception as e:
            print(f"[!] Error syncing report {report.date}: {e}")
            skipped_count += 1
    
    print(f"  Synced {synced_count} high-significance chunks to Vector DB")
    print(f"  Skipped {skipped_count} low-significance entries (audit trail only)")
    
    return memory


def generate_decision(sheet, goal, tree):
    """Generate a Decision object using ReportingAgent."""
    print("\n[STEP] Generating decision using ReportingAgent...")
    
    agent = ReportingAgent()
    
    # Get recent reports (last 7 days or all if fewer)
    recent_reports = sheet.daily_reports[-7:] if len(sheet.daily_reports) >= 7 else sheet.daily_reports
    
    print(f"  Using {len(recent_reports)} recent reports for context")
    print(f"  Goal: {goal.name}")
    print(f"  Pillar: {goal.pillars[0].value if goal.pillars else 'N/A'}")
    
    # Generate decision
    decision = agent.generate_weekly_decision(
        goal=goal,
        sheet=sheet,
        tree=tree,
        recent_reports=recent_reports,
    )
    
    return decision


def main():
    """Main test function."""
    print("=" * 60)
    print("TEST: DECISION EXPLAINABILITY WITH RUNNING DATA")
    print("=" * 60)
    
    # Step 1: Load or generate mock history
    print("\n[STEP 1] Loading mock history...")
    logs = load_or_generate_mock_history()
    
    if not logs:
        print("[X] Failed to load mock history. Exiting.")
        return
    
    print(f"  Loaded {len(logs)} log entries")
    print(f"  Date range: {logs[0]['date']} to {logs[-1]['date']}")
    
    # Step 2: Convert logs to DailyReports
    print("\n[STEP 2] Converting logs to DailyReport objects...")
    reports = convert_logs_to_daily_reports(logs)
    print(f"  Created {len(reports)} DailyReport objects")
    
    # Step 3: Create CharacterSheet with running goal
    print("\n[STEP 3] Creating CharacterSheet with running goal...")
    sheet = create_test_character_sheet(reports)
    print(f"  User ID: {sheet.user_id}")
    print(f"  Goals: {len(sheet.goals)}")
    print(f"  Daily Reports: {len(sheet.daily_reports)}")
    
    # Step 4: Sync reports to memory (with significance gate)
    memory = sync_reports_to_memory(sheet, sheet.user_id)
    
    # Step 5: Create empty SkillTree (not needed for decision generation)
    tree = SkillTree(nodes=[])
    
    # Step 6: Generate decision
    goal = sheet.goals[0]
    decision = generate_decision(sheet, goal, tree)
    
    # Step 7: Display results
    print("\n" + "=" * 60)
    print("DECISION OUTPUT")
    print("=" * 60)
    
    print(f"\nTarget: {decision.target}")
    print(f"Change: {decision.old_value} -> {decision.new_value}")
    print(f"Decision Type: {decision.decision_type}")
    print(f"Confidence: {decision.confidence_score:.2f}")
    
    print(f"\nContributing Factors: {len(decision.contributing_factors)}")
    for i, factor in enumerate(decision.contributing_factors, 1):
        verified_status = "[OK]" if factor.is_verified else "[!]"
        weight_icon = "[+]" if factor.weight == "positive" else "[-]" if factor.weight == "negative" else "[~]"
        
        print(f"\n  {verified_status} Factor {i}: {factor.factor} {weight_icon}")
        print(f"     Description: {factor.description}")
        if factor.citation_date:
            print(f"     Citation Date: {factor.citation_date}")
        if factor.verified_date and factor.verified_date != factor.citation_date:
            print(f"     Verified Date: {factor.verified_date} (CORRECTED)")
        if factor.citation_text:
            print(f"     Citation: \"{factor.citation_text[:60]}...\"")
        print(f"     Verified: {factor.is_verified}")
        if factor.verification_score:
            print(f"     Match Score: {factor.verification_score:.2f}")
    
    print(f"\nExplanation:")
    print(f"  {decision.explanation}")
    
    # Step 8: Export Decision as JSON for frontend
    print("\n" + "=" * 60)
    print("EXPORTING DECISION JSON")
    print("=" * 60)
    
    # Convert Decision to dict (Pydantic model_dump)
    decision_dict = decision.model_dump(mode="json")
    
    output_path = Path("debug/test_decision_output.json")
    output_data = {
        "decision": decision_dict,
        "metadata": {
            "generated_at": datetime.now().isoformat(),
            "goal_name": goal.name,
            "goal_id": goal.id,
            "pillar": goal.pillars[0].value if goal.pillars else None,
            "reports_count": len(reports),
            "recent_reports_count": min(len(reports), 7),
        },
        "sample_data": {
            "old_value": decision.old_value,
            "new_value": decision.new_value,
            "decision_type": decision.decision_type,
            "factors_count": len(decision.contributing_factors),
            "verified_factors_count": len([f for f in decision.contributing_factors if f.is_verified]),
        }
    }
    
    with open(output_path, "w") as f:
        json.dump(output_data, f, indent=2, default=str)
    
    print(f"\n[OK] Decision exported to: {output_path}")
    print("\nThis JSON can be used to:")
    print("  1. Load in frontend for DecisionCard component")
    print("  2. Test the 'Evidence Locker' UI")
    print("  3. Verify citation grounding and verification")
    
    print("\n" + "=" * 60)
    print("TEST COMPLETE")
    print("=" * 60)
    
    return decision, output_path


if __name__ == "__main__":
    try:
        decision, output_path = main()
        
        print("\n[OK] SUCCESS: Decision generated and exported!")
        print(f"\nNext Steps:")
        print(f"  1. Review {output_path}")
        print(f"  2. Update frontend to load this JSON")
        print(f"  3. Test DecisionCard component rendering")
        
    except Exception as e:
        print(f"\n[X] ERROR: {e}")
        import traceback
        traceback.print_exc()
