import streamlit as st
import json
import graphviz
import os

# --- PAGE CONFIGURATION ---
st.set_page_config(
    page_title="Lock In Labs: Life Architect",
    page_icon="🧬",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- CSS STYLING ---
st.markdown("""
<style>
    .stMetric {
        background-color: #f0f2f6;
        padding: 15px;
        border-radius: 10px;
        box-shadow: 2px 2px 5px rgba(0,0,0,0.1);
    }
    .stProgress .st-bo {
        background-color: #4CAF50;
    }
    h1 {
        color: #2E86C1;
    }
    div[data-testid="stExpander"] {
        border: 1px solid #ddd;
        border-radius: 5px;
    }
</style>
""", unsafe_allow_html=True)

# --- DATA LOADING ---
@st.cache_data
def load_data(filepath):
    if not os.path.exists(filepath):
        return None
    with open(filepath, "r") as f:
        return json.load(f)

# Path to the JSON file generated by main.py
# Make sure to run 'python src/main.py' first to generate this file!
DATA_FILE = "data/user_01.json" 

def main():
    st.title("🧬 Lock In Labs: Life Architect")
    st.caption("v1.0.0 - Prototype Interface")

    data = load_data(DATA_FILE)

    if not data:
        st.warning("⚠️ No Character Sheet found.")
        st.info(f"Please run `python src/main.py` to generate `{DATA_FILE}` first.")
        st.stop()

    # Handle nested structure (storage.py saves it inside 'character_sheet')
    if "character_sheet" in data:
        sheet = data["character_sheet"]
        # Merge top-level keys if needed, or just use sheet
        # The skill_tree might be at top level or inside sheet depending on version
        # storage.py saves skill_tree at top level
        skill_tree = data.get("skill_tree", sheet.get("skill_tree", {}))
    else:
        # Flat structure (legacy or simulation)
        sheet = data
        skill_tree = data.get("skill_tree", {})

    # --- SIDEBAR: PROFILE ---
    with st.sidebar:
        st.header("👤 Architect Profile")
        st.write(f"**ID:** `{sheet.get('user_id', 'Unknown')}`")
        
        st.subheader("🌟 North Star Goals")
        for goal in sheet.get("north_star_goals", []):
            st.markdown(f"- {goal}")
            
        st.divider()
        
        if "debuffs" in sheet and sheet["debuffs"]:
            st.subheader("⚠️ Active Debuffs")
            for debuff in sheet["debuffs"]:
                st.error(debuff)

    # --- HUD (HEADS UP DISPLAY) ---
    st.subheader("📊 Core Pillars")
    
    # Extract aggregate scores (average of stats) or specific key stats
    # Helper to avg a dict
    def get_avg(d):
        return round(sum(d.values()) / len(d), 1) if d else 0

    c_score = get_avg(sheet.get("stats_career", {}))
    p_score = get_avg(sheet.get("stats_physical", {}))
    m_score = get_avg(sheet.get("stats_mental", {}))
    s_score = get_avg(sheet.get("stats_social", {}))

    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("💼 Career", f"Lvl {c_score}", delta=f"{len(sheet.get('stats_career', {}))} Stats")
        with st.expander("Details"):
            st.json(sheet.get("stats_career", {}))
    with col2:
        st.metric("💪 Physical", f"Lvl {p_score}", delta=f"{len(sheet.get('stats_physical', {}))} Stats")
        with st.expander("Details"):
            st.json(sheet.get("stats_physical", {}))
    with col3:
        st.metric("🧠 Mental", f"Lvl {m_score}", delta=f"{len(sheet.get('stats_mental', {}))} Stats")
        with st.expander("Details"):
            st.json(sheet.get("stats_mental", {}))
    with col4:
        st.metric("❤️ Social", f"Lvl {s_score}", delta=f"{len(sheet.get('stats_social', {}))} Stats")
        with st.expander("Details"):
            st.json(sheet.get("stats_social", {}))

    st.divider()

    # --- SKILL TREE VISUALIZATION ---
    st.subheader("🕸️ The Neural Interface (Skill Graph)")
    
    nodes = skill_tree.get("nodes", [])
    
    if nodes:
        # Create Graphviz object
        graph = graphviz.Digraph()
        graph.attr(rankdir='BT', bgcolor='transparent') # Bottom-to-Top
        
        # Global node styles
        graph.attr('node', style='filled', fontname="Helvetica", fontsize="10", margin="0.2")
        graph.attr('edge', color='#888888', arrowsize="0.8")

        # Color Palette (Pastels)
        colors = {
            "Career": "#D6EAF8",   # Light Blue
            "Physical": "#FCF3CF", # Light Yellow
            "Mental": "#E8DAEF",   # Light Purple
            "Social": "#D5F5E3",   # Light Green
            "Default": "#FFFFFF"
        }

        for node in nodes:
            # Determine Color
            pillar = node.get("pillar", "Default")
            fill_color = colors.get(pillar, colors["Default"])
            
            # Determine Shape based on Type
            node_type = node.get("type", "Habit")
            if node_type == "Goal":
                shape = "doubleoctagon"
                fontsize = "12"
                penwidth = "2"
                fill_color = fill_color # Keep pillar color
            elif node_type == "Sub-Skill":
                shape = "box"
                fontsize = "10"
                penwidth = "1"
            else: # Habit
                shape = "oval"
                fontsize = "9"
                penwidth = "1"
                # Make habits slightly lighter/smaller
            
            # Label
            label = f"{node['name']}\n(+{node.get('xp_reward', 0)} XP)"
            
            # Tooltip (Description)
            tooltip = node.get("description", "No description")

            graph.node(
                node["id"], 
                label=label, 
                shape=shape, 
                fillcolor=fill_color, 
                fontsize=fontsize,
                penwidth=penwidth,
                tooltip=tooltip
            )
            
            # Edges
            # Prerequisites point TO this node (so Pre -> Node)
            for prereq_id in node.get("prerequisites", []):
                graph.edge(prereq_id, node["id"])

        # Render Graph
        st.graphviz_chart(graph)
        
        st.info("💡 **Legend:** Octagon = Goal | Box = Sub-Skill | Oval = Daily Habit. Colors match the Pillars above.")

    else:
        st.write("No skill tree nodes found.")

    st.divider()

    # --- QUEST LOG INTERACTION ---
    st.subheader("📜 Daily Quest Log")
    
    # Filter for Habits (Leaves of the tree)
    habits = [n for n in nodes if n.get("type") == "Habit"]
    
    if habits:
        cols = st.columns(2)
        for i, habit in enumerate(habits):
            col = cols[i % 2]
            with col:
                # Unique key needed for checkboxes
                checked = st.checkbox(
                    f"**{habit['name']}** (+{habit.get('xp_reward', 10)} XP)", 
                    key=habit['id'],
                    help=habit.get("description", "")
                )
                if checked:
                    st.toast(f"✅ Completed: {habit['name']}! Gained XP.")
    else:
        st.write("No active habits found in the tree.")

if __name__ == "__main__":
    main()